parameters:
  jenkins:
    client:
      job:
        backupninja_backup:
          type: workflow-scm
          name: backupninja-backup
          display_name: "Backupninja backup pipeline"
          discard:
            build:
              keep_num: 50
          concurrent: true
          scm:
            type: git
            url: "${_param:jenkins_gerrit_url}/mk/mk-pipelines"
            branch: "${_param:jenkins_pipelines_branch}"
            credentials: "${_param:jenkins_gerrit_credentials}"
            script: backupninja-backup-pipeline.groovy
          param:
            SALT_MASTER_CREDENTIALS:
              type: string
              default: "salt"
            SALT_MASTER_URL:
              type: string
              default: "${_param:jenkins_salt_api_url}"
            ASK_CONFIRMATION:
              type: boolean
              default: 'false'
            BACKUP_SALTMASTER_AND_MAAS:
              type: boolean
              default: 'true'
            BACKUP_DOGTAG:
              type: boolean
              default: 'false'
            BACKUP_KEYSTONE_CREDENTIAL_KEYS:
              type: boolean
              default: 'true'
          trigger:
            timer:
              enabled: true
              spec: "${_param:backup_min} ${_param:backup_hour} ${_param:backup_day_of_month} ${_param:backup_month} ${_param:backup_day_of_week}"
